import React from "react";

const CouponHistory = () => {
  // Sample JSON data
  const coupons = [
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
    {
      id: 1,
      couponCode: "SUMMER2024",
      validity: "2024-12-31",
      status: "Availed",
      generatedBy: "Admin1",
      availedBy: "JohnDoe",
    },
    {
      id: 2,
      couponCode: "WINTER2024",
      validity: "2024-11-30",
      status: "Pending",
      generatedBy: "Admin2",
      availedBy: "",
    },
    {
      id: 3,
      couponCode: "FESTIVE2024",
      validity: "2024-10-31",
      status: "Availed",
      generatedBy: "Admin3",
      availedBy: "JaneSmith",
    },
  ];

  return (
    <div className="min-h-screen bg-black-100 py-6 px-4 font-Cabin xl:text-xl">
      <h1 className="text-3xl font-bold text-center mb-6">Coupon History</h1>

      {/* Table */}
      <div className="overflow-x-auto shadow-lg rounded-lg bg-white">
        <table className="min-w-full bg-white border border-black">
          <thead>
            <tr className="text-left bg-gray-800 text-white">
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                S.No
              </th>
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                Coupon Code
              </th>
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                Validity
              </th>
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                Status
              </th>
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                Generated By
              </th>
              <th className="py-3 px-6 text-sm font-semibold border border-gray">
                Availed By
              </th>
            </tr>
          </thead>
          <tbody>
            {coupons.map((coupon, index) => (
              <tr
                key={coupon.id}
                className="group hover:bg-black hover:text-white text-left"
              >
                <td className="py-3 px-6 text-sm text-gray-700 group-hover:text-white border-t border-b border-black">
                  {index + 1}
                </td>
                <td className="py-3 px-6 text-sm text-gray-700 group-hover:text-white border-t border-l-2 border-b border-black">
                  {coupon.couponCode}
                </td>
                <td className="py-3 px-6 text-sm text-gray-700 group-hover:text-white border-t border-l-2 border-b border-black">
                  {coupon.validity}
                </td>
                <td className="py-3 px-6 text-sm text-center group-hover:text-white border-t border-l-2 border-b border-black">
                  <span
                    className={`px-3 py-1 rounded-full text-white ${
                      coupon.status === "Availed"
                        ? "bg-green-500"
                        : "bg-yellow-500"
                    }`}
                  >
                    {coupon.status}
                  </span>
                </td>
                <td className="py-3 px-6 text-sm text-gray-700 group-hover:text-white border-t border-l-2 border-b border-black">
                  {coupon.generatedBy}
                </td>
                <td className="py-3 px-6 text-sm text-left text-gray-700 group-hover:text-white border-t border-l-2 border-b border-black">
                  {coupon.status === "Availed" ? coupon.availedBy : "Pending"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default CouponHistory;
